// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/jobspb/jobs.proto

/*
Package jobspb is a generated protocol buffer package.

It is generated from these files:
	proto/jobspb/jobs.proto

It has these top-level messages:
	Job
	CreateJobRequest
	CreateJobResponse
*/
package jobspb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Job struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Image       string `protobuf:"bytes,4,opt,name=image" json:"image,omitempty"`
	Email       string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Phone       string `protobuf:"bytes,6,opt,name=phone" json:"phone,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Job) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Job) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type CreateJobRequest struct {
	Job *Job `protobuf:"bytes,1,opt,name=job" json:"job,omitempty"`
}

func (m *CreateJobRequest) Reset()                    { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()               {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateJobRequest) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type CreateJobResponse struct {
	Job *Job `protobuf:"bytes,1,opt,name=job" json:"job,omitempty"`
}

func (m *CreateJobResponse) Reset()                    { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()               {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateJobResponse) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func init() {
	proto.RegisterType((*Job)(nil), "jobspb.Job")
	proto.RegisterType((*CreateJobRequest)(nil), "jobspb.CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "jobspb.CreateJobResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for JobService service

type JobServiceClient interface {
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
}

type jobServiceClient struct {
	cc *grpc.ClientConn
}

func NewJobServiceClient(cc *grpc.ClientConn) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := grpc.Invoke(ctx, "/jobspb.JobService/CreateJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for JobService service

type JobServiceServer interface {
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
}

func RegisterJobServiceServer(s *grpc.Server, srv JobServiceServer) {
	s.RegisterService(&_JobService_serviceDesc, srv)
}

func _JobService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobspb.JobService/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jobspb.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _JobService_CreateJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/jobspb/jobs.proto",
}

func init() { proto.RegisterFile("proto/jobspb/jobs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x69, 0xeb, 0x96, 0xdd, 0x29, 0xf8, 0x27, 0x28, 0xc6, 0x45, 0x61, 0xe9, 0xc9, 0x53,
	0x8b, 0xf5, 0xe6, 0x51, 0x6f, 0x3d, 0xae, 0x07, 0xc1, 0x5b, 0xb2, 0x1d, 0x6a, 0x4a, 0xb7, 0x13,
	0x9b, 0xe8, 0x03, 0xf8, 0x02, 0x1e, 0x7c, 0x34, 0x5f, 0xc1, 0x07, 0x91, 0x24, 0xab, 0x2c, 0x22,
	0xec, 0xa9, 0x7c, 0xbf, 0xf9, 0xbe, 0x99, 0xe9, 0x04, 0x4e, 0xf5, 0x48, 0x96, 0xca, 0x8e, 0xa4,
	0xd1, 0xd2, 0x7f, 0x0a, 0x4f, 0x58, 0x1a, 0xd0, 0xfc, 0xbc, 0x25, 0x6a, 0x7b, 0x2c, 0x85, 0x56,
	0xa5, 0x18, 0x06, 0xb2, 0xc2, 0x2a, 0x1a, 0x36, 0xae, 0xfc, 0x3d, 0x82, 0xa4, 0x26, 0xc9, 0xf6,
	0x21, 0x56, 0x0d, 0x8f, 0x16, 0xd1, 0xe5, 0x6c, 0x19, 0xab, 0x86, 0x1d, 0xc3, 0xc4, 0x2a, 0xdb,
	0x23, 0x8f, 0x3d, 0x0a, 0x82, 0x2d, 0x20, 0x6b, 0xd0, 0xac, 0x46, 0xa5, 0x5d, 0x0f, 0x9e, 0xf8,
	0xda, 0x36, 0x72, 0x39, 0xb5, 0x16, 0x2d, 0xf2, 0xbd, 0x90, 0xf3, 0xc2, 0x51, 0x5c, 0x0b, 0xd5,
	0xf3, 0x49, 0xa0, 0x5e, 0x38, 0xaa, 0x9f, 0x68, 0x40, 0x9e, 0x06, 0xea, 0x45, 0x7e, 0x05, 0x87,
	0x77, 0x23, 0x0a, 0x8b, 0x35, 0xc9, 0x25, 0x3e, 0xbf, 0xa0, 0xb1, 0xec, 0x02, 0x92, 0x8e, 0xa4,
	0x5f, 0x2f, 0xab, 0xb2, 0x22, 0xfc, 0x59, 0xe1, 0x0c, 0x8e, 0xe7, 0x15, 0x1c, 0x6d, 0x45, 0x8c,
	0xa6, 0xc1, 0xe0, 0x8e, 0x4c, 0x85, 0x00, 0x35, 0xc9, 0x7b, 0x1c, 0x5f, 0xd5, 0x0a, 0xd9, 0x03,
	0xcc, 0x7e, 0x3b, 0x30, 0xfe, 0x63, 0xfe, 0xbb, 0xc7, 0xfc, 0xec, 0x9f, 0x4a, 0x18, 0x97, 0x9f,
	0xbc, 0x7d, 0x7e, 0x7d, 0xc4, 0x07, 0xf9, 0xd4, 0x1f, 0xba, 0x23, 0x79, 0xe3, 0xc6, 0xdc, 0x4e,
	0x1f, 0x37, 0xef, 0x20, 0x53, 0x7f, 0xf0, 0xeb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x07, 0xf5,
	0xb4, 0x18, 0xb1, 0x01, 0x00, 0x00,
}
