// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/jobspb/jobs.proto

package jobspb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Image                string   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_6861afb2870b5e94, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Job) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Job) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type CreateJobRequest struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobRequest) Reset()         { *m = CreateJobRequest{} }
func (m *CreateJobRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJobRequest) ProtoMessage()    {}
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6861afb2870b5e94, []int{1}
}

func (m *CreateJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobRequest.Unmarshal(m, b)
}
func (m *CreateJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobRequest.Marshal(b, m, deterministic)
}
func (m *CreateJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobRequest.Merge(m, src)
}
func (m *CreateJobRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJobRequest.Size(m)
}
func (m *CreateJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobRequest proto.InternalMessageInfo

func (m *CreateJobRequest) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type CreateJobResponse struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJobResponse) Reset()         { *m = CreateJobResponse{} }
func (m *CreateJobResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJobResponse) ProtoMessage()    {}
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6861afb2870b5e94, []int{2}
}

func (m *CreateJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJobResponse.Unmarshal(m, b)
}
func (m *CreateJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJobResponse.Marshal(b, m, deterministic)
}
func (m *CreateJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJobResponse.Merge(m, src)
}
func (m *CreateJobResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJobResponse.Size(m)
}
func (m *CreateJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJobResponse proto.InternalMessageInfo

func (m *CreateJobResponse) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type GetAllJobsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllJobsRequest) Reset()         { *m = GetAllJobsRequest{} }
func (m *GetAllJobsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllJobsRequest) ProtoMessage()    {}
func (*GetAllJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6861afb2870b5e94, []int{3}
}

func (m *GetAllJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllJobsRequest.Unmarshal(m, b)
}
func (m *GetAllJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllJobsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllJobsRequest.Merge(m, src)
}
func (m *GetAllJobsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllJobsRequest.Size(m)
}
func (m *GetAllJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllJobsRequest proto.InternalMessageInfo

type GetAllJobsResponse struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllJobsResponse) Reset()         { *m = GetAllJobsResponse{} }
func (m *GetAllJobsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllJobsResponse) ProtoMessage()    {}
func (*GetAllJobsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6861afb2870b5e94, []int{4}
}

func (m *GetAllJobsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllJobsResponse.Unmarshal(m, b)
}
func (m *GetAllJobsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllJobsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllJobsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllJobsResponse.Merge(m, src)
}
func (m *GetAllJobsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllJobsResponse.Size(m)
}
func (m *GetAllJobsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllJobsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllJobsResponse proto.InternalMessageInfo

func (m *GetAllJobsResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func init() {
	proto.RegisterType((*Job)(nil), "jobspb.Job")
	proto.RegisterType((*CreateJobRequest)(nil), "jobspb.CreateJobRequest")
	proto.RegisterType((*CreateJobResponse)(nil), "jobspb.CreateJobResponse")
	proto.RegisterType((*GetAllJobsRequest)(nil), "jobspb.GetAllJobsRequest")
	proto.RegisterType((*GetAllJobsResponse)(nil), "jobspb.GetAllJobsResponse")
}

func init() { proto.RegisterFile("proto/jobspb/jobs.proto", fileDescriptor_6861afb2870b5e94) }

var fileDescriptor_6861afb2870b5e94 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xd2, 0x96, 0x76, 0x0a, 0xda, 0xae, 0x8a, 0x6b, 0x50, 0x2c, 0x39, 0x79, 0x6a,
	0xb1, 0xe2, 0xc5, 0x9b, 0x7a, 0x10, 0x72, 0xac, 0x88, 0xe0, 0x2d, 0xdb, 0x0e, 0x75, 0x4b, 0x9a,
	0x89, 0xc9, 0xea, 0x03, 0xf8, 0x02, 0x1e, 0x7c, 0x1d, 0xdf, 0xc2, 0x57, 0xf0, 0x41, 0x64, 0x67,
	0x63, 0x0d, 0xb5, 0xe0, 0x29, 0xcc, 0x37, 0xf3, 0xff, 0xfb, 0x0f, 0x19, 0xd8, 0xcf, 0x0b, 0x32,
	0x34, 0x5a, 0x90, 0x2a, 0x73, 0xc5, 0x9f, 0x21, 0x13, 0xd1, 0x72, 0x28, 0x3c, 0x9c, 0x13, 0xcd,
	0x53, 0x1c, 0x25, 0xb9, 0x1e, 0x25, 0x59, 0x46, 0x26, 0x31, 0x9a, 0xb2, 0x6a, 0x2a, 0x7a, 0xf3,
	0x20, 0x88, 0x49, 0x89, 0x2d, 0xf0, 0xf5, 0x4c, 0x7a, 0x03, 0xef, 0xa4, 0x33, 0xf1, 0xf5, 0x4c,
	0xec, 0x42, 0xd3, 0x68, 0x93, 0xa2, 0xf4, 0x19, 0xb9, 0x42, 0x0c, 0xa0, 0x3b, 0xc3, 0x72, 0x5a,
	0xe8, 0xdc, 0x7a, 0xc8, 0x80, 0x7b, 0x75, 0x64, 0x75, 0x7a, 0x99, 0xcc, 0x51, 0x36, 0x9c, 0x8e,
	0x0b, 0x4b, 0x71, 0x99, 0xe8, 0x54, 0x36, 0x1d, 0xe5, 0xc2, 0xd2, 0xfc, 0x91, 0x32, 0x94, 0x2d,
	0x47, 0xb9, 0x88, 0x4e, 0xa1, 0x77, 0x5d, 0x60, 0x62, 0x30, 0x26, 0x35, 0xc1, 0xa7, 0x67, 0x2c,
	0x8d, 0x38, 0x82, 0x60, 0x41, 0x8a, 0xe3, 0x75, 0xc7, 0xdd, 0xa1, 0xdb, 0x6c, 0x68, 0x07, 0x2c,
	0x8f, 0xc6, 0xd0, 0xaf, 0x49, 0xca, 0x9c, 0xb2, 0x12, 0xff, 0xd3, 0xec, 0x40, 0xff, 0x06, 0xcd,
	0x65, 0x9a, 0xc6, 0xa4, 0xca, 0xea, 0x9d, 0xe8, 0x1c, 0x44, 0x1d, 0x56, 0x4e, 0xc7, 0xd0, 0xb0,
	0x6a, 0xe9, 0x0d, 0x82, 0x75, 0x2b, 0x6e, 0x8c, 0x3f, 0x3c, 0x80, 0x98, 0xd4, 0x2d, 0x16, 0x2f,
	0x7a, 0x8a, 0xe2, 0x1e, 0x3a, 0xab, 0x38, 0x42, 0xfe, 0x8c, 0xaf, 0x2f, 0x15, 0x1e, 0x6c, 0xe8,
	0xb8, 0x17, 0xa3, 0xbd, 0xd7, 0xcf, 0xaf, 0x77, 0x7f, 0x3b, 0x6a, 0xf3, 0x5f, 0x5b, 0x90, 0xba,
	0xb0, 0x99, 0xc5, 0x1d, 0xc0, 0x6f, 0x3c, 0xb1, 0xd2, 0xff, 0xd9, 0x23, 0x0c, 0x37, 0xb5, 0x2a,
	0xef, 0x1e, 0x7b, 0x83, 0x58, 0x79, 0x5f, 0xb5, 0x1f, 0xaa, 0x5b, 0x51, 0x2d, 0x3e, 0x8a, 0xb3,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xe9, 0x23, 0xac, 0x55, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobServiceClient interface {
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
	GetAllJobs(ctx context.Context, in *GetAllJobsRequest, opts ...grpc.CallOption) (*GetAllJobsResponse, error)
}

type jobServiceClient struct {
	cc *grpc.ClientConn
}

func NewJobServiceClient(cc *grpc.ClientConn) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, "/jobspb.JobService/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetAllJobs(ctx context.Context, in *GetAllJobsRequest, opts ...grpc.CallOption) (*GetAllJobsResponse, error) {
	out := new(GetAllJobsResponse)
	err := c.cc.Invoke(ctx, "/jobspb.JobService/GetAllJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServiceServer is the server API for JobService service.
type JobServiceServer interface {
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	GetAllJobs(context.Context, *GetAllJobsRequest) (*GetAllJobsResponse, error)
}

// UnimplementedJobServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJobServiceServer struct {
}

func (*UnimplementedJobServiceServer) CreateJob(ctx context.Context, req *CreateJobRequest) (*CreateJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJob not implemented")
}
func (*UnimplementedJobServiceServer) GetAllJobs(ctx context.Context, req *GetAllJobsRequest) (*GetAllJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllJobs not implemented")
}

func RegisterJobServiceServer(s *grpc.Server, srv JobServiceServer) {
	s.RegisterService(&_JobService_serviceDesc, srv)
}

func _JobService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobspb.JobService/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetAllJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetAllJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jobspb.JobService/GetAllJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetAllJobs(ctx, req.(*GetAllJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jobspb.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _JobService_CreateJob_Handler,
		},
		{
			MethodName: "GetAllJobs",
			Handler:    _JobService_GetAllJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/jobspb/jobs.proto",
}
